### ISSUE TITLE
CSS does not load correctly on build-screen

### ISSUE THREAD

**Issue by mookjp** [mookjp/pool#130]
On Vagrant environment, pool returns build-screen without stylesheet.

**Comment by ainoya** [comment]
I can't reproduce the bug you reported in my environment.
Does the bug always occur ? Please report the logs (apache, build_server.log, etc...) when the bug happened if you can.

**Comment by mookjp** [comment]
@ainoya After I deleted `docker/pool/builder/vendor`, it does not happen anymore. I'm sorry for confusing you.
