### ISSUE TITLE
cannot vagrant ssh after vagrant halt

### ISSUE THREAD

**Issue by srym** [mookjp/pool#146]
```bash
$ vagrant up
$ vagrant ssh  # ok
C-d

$ vagrant halt
$ vagrant up
$ vagrant ssh
core@127.0.0.1's password:
core@127.0.0.1's password:
core@127.0.0.1's password:
Permission denied (publickey,password,keyboard-interactive).

$ vagrant ssh-config # the same result as before
Host default
  HostName 127.0.0.1
  User core
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/shiroyama/git/pool/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL

 $ vagrant -v
Vagrant 1.7.2
```

cloneしてサラピンの状態で `vagrant up` したら普通に `vagrant ssh` できるんですが一度 `vagrant halt` すると以後二度とsshできなくなります。必ず再現します。
秘密鍵は変わっていないのですが、もし何かご存知なら教えていただきたいです。僕のvagrantに関する無知に起因する問題ならすみません。

ちょっと評価するのにvagrantは非常に好都合なので、お暇な時に分かったら嬉しいです。

**Comment by mookjp** [comment]
@srym 
報告ありがとうございます。
以下の私の環境でも再現されることが確認できました。
> coreos-alpha (virtualbox, 626.0.0)

https://github.com/coreos/docs/issues/10
こちらのIssueでvagrantの挙動がかわり、coreosのイメージで用意している鍵をvagrantが上書きしてしまっているため起こっているようだという会話がありました。
`Vagrantfile`内に`config.ssh.insert_key = false`を追加することで再度`vagrant ssh`できることが確認できたので、ひとまずVagrantfileを修正します。
マージされるまでは、上記を追記してみていただけないでしょうか。

**Comment by srym** [comment]
pullして手元でhalt and up後も再度sshできることを確認しました～！すごい嬉しいです。ありがとうございます。
